### ISSUE TITLE
How to manually preprocess the LIDC dataset folder before running the script?

### ISSUE THREAD

**Issue by cpuxzb** [mikejhuang/LungNoduleDetectionClassification#9]
LIDC file folder
https://github.com/cpuxzb/Question/blob/master/folder.png
When I run the '1. Process Nodule Dataset.ipynb',following code block generates a null datfolder variable.
https://github.com/cpuxzb/Question/blob/master/error%20code.JPG

**Comment by spx1997** [comment]
hi, this problem is caused by different folder organization. In older downloads,  the data DICOM data would download as:`[...]/LIDC-IDRI/LIDC-IDRI-dddd/uid1/uid2/dicom_file.dcm`. However, in more recent downloads, the data is downloaded like: `[...]/LIDC-IDRI/LIDC-IDRI-dddd/???`.  Your can go to [pylidc](https://github.com/notmatthancock/pylidc/blob/master/pylidc/Scan.py) for more detail.
good luck!
